# general settings
name: train_HATRCF_SRx4_from_scratch
model_type: HATModel # The model type in the training pipeline will use the registered HAT_RCF
scale: 4
num_gpu: auto
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: AID_train
    type: PairedImageDataset
    dataroot_gt: datasets/train/HR
    dataroot_lq: datasets/train/LR_x4
    meta_info_file: hat/data/meta_info/meta_info_AID_GT.txt
    io_backend:
      type: disk

    gt_size: 256
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val_1:
    name: AID_val
    type: PairedImageDataset
    dataroot_gt: ./datasets/val/HR
    dataroot_lq: ./datasets/val/LR_x4
    io_backend:
      type: disk

# network structures
network_g:
  type: HAT_RCF # Use HAT_RCF model
  rcf_pretrained_path: pretrained_model/RCF-BSDS.pth # RCF weights
  upscale: 4
  in_chans: 3
  img_size: 64
  window_size: 16
  compress_ratio: 3
  squeeze_factor: 30
  conv_scale: 0.01
  overlap_ratio: 0.5
  img_range: 1.
  depths: [6, 6, 6, 6, 6, 6]
  embed_dim: 180
  num_heads: [6, 6, 6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'

# path
path:
  pretrain_network_g: ~ # Training from scratch
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [300000, 500000, 650000, 700000, 750000]
    gamma: 0.5

  total_iter: 200000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 1e2
  save_img: true
  pbar: False

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 4
      test_y_channel: true
      better: higher
    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: true
      better: higher

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e4
  use_tb_logger: true
  wandb:
    project: zee_aid
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
